# Generated by Django 4.1.4 on 2022-12-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reto", "0003_remove_album_artist_remove_song_artist_artist_album"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="artist",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="song",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
