# Generated by Django 4.1.4 on 2022-12-20 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reto", "0004_alter_album_id_alter_artist_id_alter_song_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="songs",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="album",
        ),
        migrations.AddField(
            model_name="album",
            name="artist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reto.artist",
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="album",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="reto.album"
            ),
        ),
    ]
